language: node_js
node_js:
  - "6"
  - "node"

cache: yarn
before_install:
  - nvm install 7
  - nvm use 7
before_script:
  - yarn run build:node
  - yarn run build:test
  - nvm use $TRAVIS_NODE_VERSION